# Generated by Django 2.2.4 on 2020-12-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
