# Generated by Django 2.2.4 on 2020-12-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='HELLO', max_length=255),
            preserve_default=False,
        ),
    ]
