# Generated by Django 2.2.4 on 2020-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorApp', '0002_author_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='Authors', to='booksAuthorApp.Book'),
        ),
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(),
        ),
    ]
